---
- name: Create pods using deployment 
  hosts: kube 
  # become: true
  user: ubuntu
 
  tasks: 
  - name: create a deployment
    command: kubectl apply -f kj-deployment.yaml 
    args:
      chdir: /home/ubuntu/kubedata 

  - name: update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment.apps/kj-deployment
